### ISSUE TITLE
volume

### ISSUE THREAD

**Issue by cbaum123** [ga-dc/class-tweeter#4]
We have 4 info sessions a week all scheduled and on the website two months in advance, even with cadence we will have multiple tweets going out per day/week and don't want to overwhelm our twitter audience. 

feature certain courses? highlight the info sessions associated with specific launches?

**Comment by jshawl** [comment]
are the info sessions on separate days? if so, this should not be a problem

**Comment by cbaum123** [comment]
1 info session a day!

**Comment by jshawl** [comment]
exccceeeelllllnet. currently shceduled to tweet once a day every day at 9:20 am can change
